<a href="https://colab.research.google.com/github/merttguney/AI_106/blob/main/AI106_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [275]:
import numpy as np

In [276]:
np.random.random((3, 3))

array([[0.92486653, 0.85790242, 0.11031401],
       [0.19833874, 0.34939099, 0.25448706],
       [0.91977384, 0.14806513, 0.01932197]])

In [277]:
np.random.randint(0, 20, 4)

array([15,  3,  2,  6])

In [278]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [279]:
a + 4

array([4, 5, 6, 7])

In [280]:
a * 2

array([0, 2, 4, 6])

In [281]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [282]:
a

array([0, 1, 2, 3])

In [283]:
a + b

array([ 4,  6,  8, 10])

In [284]:
a * b

array([ 0,  5, 12, 21])

In [285]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [286]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [287]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [288]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [289]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [290]:
np.dot(A, B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [291]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [292]:
a += 1
a

array([1, 2, 3, 4])

In [293]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [294]:
a.sum()

15.0

In [295]:
a.min()

0.3

In [296]:
a.max()

5.7

In [297]:
a.std()

2.0079840636817816

In [298]:
a.mean()

3.0

In [299]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [300]:
a[4]

14

In [301]:
a[-1]

15

In [302]:
a[[1, 3, 4]]

array([11, 13, 14])

In [303]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [304]:
A[2, 1]

17

In [305]:
A[[0,1],[1,2]]

array([11, 15])

In [306]:
A[1, [1,2]]

array([14, 15])

In [307]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [308]:
a[1:5]

array([11, 12, 13, 14])

In [309]:
a[1:5:2]

array([11, 13])

In [310]:
a[:2]

array([10, 11])

In [311]:
a[2:]

array([12, 13, 14, 15])

In [312]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [313]:
A[0, :]

array([10, 11, 12])

In [314]:
A[:-1]

array([[10, 11, 12],
       [13, 14, 15]])

In [315]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

# PANDAS

In [316]:
# Numpy, sayılarla daha kolay çalışmamızı sağlarken, pandas ise veri setleri ile kolay çalışmamızı sağlayan bir kütüphanedir.
# Özellikle de yapılandırılmış verilerle kolay çalışmamızı sağlar. Yapılandırılmış veri : Satır ve sütunlar olan veriler(excel verileri, veritabanı tabloları).
# Yapılandırılmamış veri : Ses, görsel, metin, yorum, içerik.

In [317]:
import pandas as pd

In [318]:
isimler = ['mert', 'ali', 'veli']
soy_isimler = ['demir', 'demir', 'demir']
yaslar = [23, 24, 25]

In [319]:
veri = {
    "ad" : isimler,
    "soyad" : soy_isimler,
    "yas" : yaslar
}

veri

{'ad': ['mert', 'ali', 'veli'],
 'soyad': ['demir', 'demir', 'demir'],
 'yas': [23, 24, 25]}

In [320]:
ogrenciler = pd.DataFrame(veri)
ogrenciler

ad  soyad  yas
0  mert  demir   23
1   ali  demir   24
2  veli  demir   25

In [321]:
veri = [['zafer', 'demirkol', 43],
        ['mert', 'demir', 23],
        ['ali', 'demir', 24],
        ['veli', 'demir', 25]

]
veri

[['zafer', 'demirkol', 43],
 ['mert', 'demir', 23],
 ['ali', 'demir', 24],
 ['veli', 'demir', 25]]

In [322]:
sütun_isimleri = ['ad', 'soyad', 'yas']
ogrenciler = pd.DataFrame(veri, columns=sütun_isimleri)
ogrenciler

ad     soyad  yas
0  zafer  demirkol   43
1   mert     demir   23
2    ali     demir   24
3   veli     demir   25

In [323]:
import numpy as np
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
                                          index = ['kırmızı', 'mavi', 'sarı', 'beyaz'],
                                          columns = ['top', 'kalem', 'kağıt', 'fincan'])
frame


top  kalem  kağıt  fincan
kırmızı    0      1      2       3
mavi       4      5      6       7
sarı       8      9     10      11
beyaz     12     13     14      15

In [324]:
x = "kalem"
frame[x]

kırmızı     1
mavi        5
sarı        9
beyaz      13
Name: kalem, dtype: int64

In [325]:
frame.kalem

kırmızı     1
mavi        5
sarı        9
beyaz      13
Name: kalem, dtype: int64

In [326]:
frame[["kalem", "fincan"]]

kalem  fincan
kırmızı      1       3
mavi         5       7
sarı         9      11
beyaz       13      15

In [327]:
frame["kalem"][0:2]

kırmızı    1
mavi       5
Name: kalem, dtype: int64

In [328]:
frame["kalem"]

kırmızı     1
mavi        5
sarı        9
beyaz      13
Name: kalem, dtype: int64

In [329]:
frame["kalem"][[2]]

<ipython-input-329-5a3e41f97975>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  frame["kalem"][[2]]


sarı    9
Name: kalem, dtype: int64

In [330]:
frame

top  kalem  kağıt  fincan
kırmızı    0      1      2       3
mavi       4      5      6       7
sarı       8      9     10      11
beyaz     12     13     14      15

In [331]:
frame.iloc[1:3]

top  kalem  kağıt  fincan
mavi    4      5      6       7
sarı    8      9     10      11

In [332]:
frame.iloc[1:3, 1:2]

kalem
mavi      5
sarı      9

In [333]:
frame

top  kalem  kağıt  fincan
kırmızı    0      1      2       3
mavi       4      5      6       7
sarı       8      9     10      11
beyaz     12     13     14      15

In [334]:
frame.loc["kırmızı":"sarı"]

top  kalem  kağıt  fincan
kırmızı    0      1      2       3
mavi       4      5      6       7
sarı       8      9     10      11

In [335]:
# frame.loc[1:3] hata

In [336]:
frame.loc["kırmızı":"sarı", "kalem":"fincan"]

kalem  kağıt  fincan
kırmızı      1      2       3
mavi         5      6       7
sarı         9     10      11

In [337]:
frame.loc[['kırmızı', 'beyaz']]

top  kalem  kağıt  fincan
kırmızı    0      1      2       3
beyaz     12     13     14      15

In [338]:
veriler = pd.read_table("http://bit.ly/chiporders")
veriler

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

In [339]:
type(veriler)

pandas.core.frame.DataFrame

In [340]:
veriler.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [341]:
veriler.tail(13)

order_id  quantity            item_name  \
4609      1829         1    Canned Soft Drink   
4610      1830         1        Steak Burrito   
4611      1830         1       Veggie Burrito   
4612      1831         1        Carnitas Bowl   
4613      1831         1                Chips   
4614      1831         1        Bottled Water   
4615      1832         1   Chicken Soft Tacos   
4616      1832         1  Chips and Guacamole   
4617      1833         1        Steak Burrito   
4618      1833         1        Steak Burrito   
4619      1834         1   Chicken Salad Bowl   
4620      1834         1   Chicken Salad Bowl   
4621      1834         1   Chicken Salad Bowl   

                                     choice_description item_price  
4609                                           [Sprite]     $1.25   
4610  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4611  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...    $11.25   
4612  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $9.25   
4613                                                NaN     $2.15   
4614                                                NaN     $1.50   
4615   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $8.75   
4616                                                NaN     $4.45   
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

In [342]:
sutunlar = ["id", "yas", "cinsiyet", "meslek", "zip_code"]

izleyiciler = pd.read_table("http://bit.ly/movieusers", sep="|", names=sutunlar)
izleyiciler

id  yas cinsiyet         meslek zip_code
0      1   24        M     technician    85711
1      2   53        F          other    94043
2      3   23        M         writer    32067
3      4   24        M     technician    43537
4      5   33        F          other    15213
..   ...  ...      ...            ...      ...
938  939   26        F        student    33319
939  940   32        M  administrator    02215
940  941   20        M        student    97229
941  942   48        F      librarian    78209
942  943   22        M        student    77841

[943 rows x 5 columns]

In [343]:
ufo = pd.read_csv("http://bit.ly/uforeports")
ufo

City Colors Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [344]:
ufo.describe().T

count unique               top  freq
City             18215   6475           Seattle   187
Colors Reported   2882     27               RED   780
Shape Reported   15597     27             LIGHT  2803
State            18241     52                CA  2529
Time             18241  16145  11/16/1999 19:00    27

In [345]:
ufo["City"]

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...         
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [346]:
ufo.City

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...         
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [347]:
ufo[["City", "Time"]]

City              Time
0                    Ithaca    6/1/1930 22:00
1               Willingboro   6/30/1930 20:00
2                   Holyoke   2/15/1931 14:00
3                   Abilene    6/1/1931 13:00
4      New York Worlds Fair   4/18/1933 19:00
...                     ...               ...
18236            Grant Park  12/31/2000 23:00
18237           Spirit Lake  12/31/2000 23:00
18238           Eagle River  12/31/2000 23:45
18239           Eagle River  12/31/2000 23:45
18240                  Ybor  12/31/2000 23:59

[18241 rows x 2 columns]

In [348]:
ufo[3:6]

City Colors Reported Shape Reported State             Time
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00
5           Valley City             NaN           DISK    ND  9/15/1934 15:30

In [349]:
ufo.iloc[2]

City                       Holyoke
Colors Reported                NaN
Shape Reported                OVAL
State                           CO
Time               2/15/1931 14:00
Name: 2, dtype: object

In [350]:
ufo.iloc[2]

City                       Holyoke
Colors Reported                NaN
Shape Reported                OVAL
State                           CO
Time               2/15/1931 14:00
Name: 2, dtype: object

In [351]:
ufo.loc[2:4]

City Colors Reported Shape Reported State             Time
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [352]:
ufo.iloc[2:4]

City Colors Reported Shape Reported State             Time
2  Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3  Abilene             NaN           DISK    KS   6/1/1931 13:00

In [353]:
ufo.loc[:3, "City"]

0         Ithaca
1    Willingboro
2        Holyoke
3        Abilene
Name: City, dtype: object

In [354]:
ufo[ "City"][:4]

0         Ithaca
1    Willingboro
2        Holyoke
3        Abilene
Name: City, dtype: object

In [355]:
ufo.loc[:3, ["City", "Time"]]

City             Time
0       Ithaca   6/1/1930 22:00
1  Willingboro  6/30/1930 20:00
2      Holyoke  2/15/1931 14:00
3      Abilene   6/1/1931 13:00

In [356]:
ufo

City Colors Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [357]:
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='object')

In [358]:
#ufo.Colors Reported

In [359]:
ufo.columns = ufo.columns.str.replace(' ', '_')

In [360]:
ufo.columns

Index(['City', 'Colors_Reported', 'Shape_Reported', 'State', 'Time'], dtype='object')

In [361]:
ufo

City Colors_Reported Shape_Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [362]:
ufo2 = ufo.drop(["City", "State"], axis=1, inplace=False)

In [363]:
ufo2

Colors_Reported Shape_Reported              Time
0                 NaN       TRIANGLE    6/1/1930 22:00
1                 NaN          OTHER   6/30/1930 20:00
2                 NaN           OVAL   2/15/1931 14:00
3                 NaN           DISK    6/1/1931 13:00
4                 NaN          LIGHT   4/18/1933 19:00
...               ...            ...               ...
18236             NaN       TRIANGLE  12/31/2000 23:00
18237             NaN           DISK  12/31/2000 23:00
18238             NaN            NaN  12/31/2000 23:45
18239             RED          LIGHT  12/31/2000 23:45
18240             NaN           OVAL  12/31/2000 23:59

[18241 rows x 3 columns]

In [364]:
ufo

City Colors_Reported Shape_Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [365]:
movies = pd.read_csv("http://bit.ly/imdbratings")
movies

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [366]:
movies.sort_values("title", ascending=True)

star_rating                  title content_rating      genre  duration  \
542          7.8   (500) Days of Summer          PG-13     Comedy        95   
5            8.9           12 Angry Men      NOT RATED      Drama        96   
201          8.1       12 Years a Slave              R  Biography       134   
698          7.6              127 Hours              R  Adventure        94   
110          8.3  2001: A Space Odyssey              G    Mystery       160   
..           ...                    ...            ...        ...       ...   
955          7.4       Zero Dark Thirty              R      Drama       157   
677          7.7                 Zodiac              R      Crime       157   
615          7.7             Zombieland              R     Comedy        88   
526          7.8                   Zulu        UNRATED      Drama       138   
864          7.5                  [Rec]              R     Horror        78   

                                           actors_list  
542  [u'Zooey Deschanel', u'Joseph Gordon-Levitt', ...  
5    [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
201  [u'Chiwetel Ejiofor', u'Michael Kenneth Willia...  
698  [u'James Franco', u'Amber Tamblyn', u'Kate Mara']  
110  [u'Keir Dullea', u'Gary Lockwood', u'William S...  
..                                                 ...  
955  [u'Jessica Chastain', u'Joel Edgerton', u'Chri...  
677  [u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M...  
615  [u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha...  
526  [u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac...  
864  [u'Manuela Velasco', u'Ferran Terraza', u'Jorg...  

[979 rows x 6 columns]

In [367]:
movies[movies.duration >= 200]

star_rating                                          title  \
2            9.1                         The Godfather: Part II   
7            8.9  The Lord of the Rings: The Return of the King   
17           8.7                                  Seven Samurai   
78           8.4                    Once Upon a Time in America   
85           8.4                             Lawrence of Arabia   
142          8.3              Lagaan: Once Upon a Time in India   
157          8.2                             Gone with the Wind   
204          8.1                                        Ben-Hur   
445          7.9                           The Ten Commandments   
476          7.8                                         Hamlet   
630          7.7                                      Malcolm X   
767          7.6                It's a Mad, Mad, Mad, Mad World   

    content_rating      genre  duration  \
2                R      Crime       200   
7            PG-13  Adventure       201   
17         UNRATED      Drama       207   
78               R      Crime       229   
85              PG  Adventure       216   
142             PG  Adventure       224   
157              G      Drama       238   
204              G  Adventure       212   
445       APPROVED  Adventure       220   
476          PG-13      Drama       242   
630          PG-13  Biography       202   
767       APPROVED     Action       205   

                                           actors_list  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
7    [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
17   [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...  
78   [u'Robert De Niro', u'James Woods', u'Elizabet...  
85   [u"Peter O'Toole", u'Alec Guinness', u'Anthony...  
142  [u'Aamir Khan', u'Gracy Singh', u'Rachel Shell...  
157  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
204  [u'Charlton Heston', u'Jack Hawkins', u'Stephe...  
445  [u'Charlton Heston', u'Yul Brynner', u'Anne Ba...  
476  [u'Kenneth Branagh', u'Julie Christie', u'Dere...  
630  [u'Denzel Washington', u'Angela Bassett', u'De...  
767  [u'Spencer Tracy', u'Milton Berle', u'Ethel Me...

In [368]:
movies[(movies.duration >= 200) & (movies.genre == "Drama")]

star_rating               title content_rating  genre  duration  \
17           8.7       Seven Samurai        UNRATED  Drama       207   
157          8.2  Gone with the Wind              G  Drama       238   
476          7.8              Hamlet          PG-13  Drama       242   

                                           actors_list  
17   [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...  
157  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
476  [u'Kenneth Branagh', u'Julie Christie', u'Dere...

In [369]:
movies[(movies.duration >= 200) | (movies.genre == "Drama")]

star_rating                                          title  \
2            9.1                         The Godfather: Part II   
5            8.9                                   12 Angry Men   
7            8.9  The Lord of the Rings: The Return of the King   
9            8.9                                     Fight Club   
13           8.8                                   Forrest Gump   
..           ...                                            ...   
958          7.4                             My Sister's Keeper   
968          7.4                            The English Patient   
970          7.4                                    Wonder Boys   
972          7.4                                 Blue Valentine   
973          7.4                          The Cider House Rules   

    content_rating      genre  duration  \
2                R      Crime       200   
5        NOT RATED      Drama        96   
7            PG-13  Adventure       201   
9                R      Drama       139   
13           PG-13      Drama       142   
..             ...        ...       ...   
958          PG-13      Drama       109   
968              R      Drama       162   
970              R      Drama       107   
972          NC-17      Drama       112   
973          PG-13      Drama       126   

                                           actors_list  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
5    [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
7    [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
9    [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...  
13     [u'Tom Hanks', u'Robin Wright', u'Gary Sinise']  
..                                                 ...  
958  [u'Cameron Diaz', u'Abigail Breslin', u'Alec B...  
968  [u'Ralph Fiennes', u'Juliette Binoche', u'Will...  
970  [u'Michael Douglas', u'Tobey Maguire', u'Franc...  
972  [u'Ryan Gosling', u'Michelle Williams', u'John...  
973  [u'Tobey Maguire', u'Charlize Theron', u'Micha...  

[287 rows x 6 columns]

In [370]:
movies[(movies.duration < 200) & (movies.duration > 100) ]

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
6            8.9                   The Good, the Bad and the Ugly   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
3            PG-13     Action       152   
4                R      Crime       154   
6        NOT RATED    Western       161   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
6    [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[757 rows x 6 columns]

In [371]:
#excel_data_df = pd.read_excel("personel.xlsx" , sheet_name='calisanlar',
                           #   usecols=['id', 'Ad', 'Meslek'])

#openpyxl

In [372]:
#excel_data_df

In [373]:
tables = pd.read_html("https://en.wikipedia.org/wiki/2020_Summer_Olympics", match="2020 Summer Olympics medal table")

In [374]:
tables

[                   Rank                  NOC  Gold  Silver  Bronze  Total
 0                     1        United States    39      41      33    113
 1                     2                China    38      32      19     89
 2                     3               Japan*    27      14      17     58
 3                     4        Great Britain    22      20      22     64
 4                     5                  ROC    20      28      23     71
 5                     6            Australia    17       7      22     46
 6                     7          Netherlands    10      12      14     36
 7                     8               France    10      12      11     33
 8                     9              Germany    10      11      16     37
 9                    10                Italy    10      10      20     40
 10                11–93            Remaining   137     151     205    493
 11  Totals (93 entries)  Totals (93 entries)   340     338     402   1080]

In [375]:
df = pd.DataFrame(np.arange(0, 15).reshape(5, 3),
                                 index=['a', 'b', 'c', 'd', 'e'],
                                 columns=['c1', 'c2', 'c3'])

df

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14

In [376]:
df['c4'] = np.nan

In [377]:
df

c1  c2  c3  c4
a   0   1   2 NaN
b   3   4   5 NaN
c   6   7   8 NaN
d   9  10  11 NaN
e  12  13  14 NaN

In [378]:
df.loc['f'] = np.arange(15, 19)

In [379]:
df

c1  c2  c3    c4
a   0   1   2   NaN
b   3   4   5   NaN
c   6   7   8   NaN
d   9  10  11   NaN
e  12  13  14   NaN
f  15  16  17  18.0

In [380]:
df.loc['g'] = np.nan

In [381]:
df

c1    c2    c3    c4
a   0.0   1.0   2.0   NaN
b   3.0   4.0   5.0   NaN
c   6.0   7.0   8.0   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   NaN
f  15.0  16.0  17.0  18.0
g   NaN   NaN   NaN   NaN

In [382]:
df['c5'] = np.nan

In [383]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0   NaN NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [384]:
df['c4']['a'] = 20

<ipython-input-384-a07c4e4235ba>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['c4']['a'] = 20


In [385]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [386]:
df.isnull().sum()

c1    1
c2    1
c3    1
c4    5
c5    7
dtype: int64

In [387]:
df.isnull().sum().sum()

15

In [388]:
df.c4.dropna()

a    20.0
f    18.0
Name: c4, dtype: float64

In [389]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [390]:
df.dropna(how='all', axis=1, inplace=False)

c1    c2    c3    c4
a   0.0   1.0   2.0  20.0
b   3.0   4.0   5.0   NaN
c   6.0   7.0   8.0   NaN
d   9.0  10.0  11.0   NaN
e  12.0  13.0  14.0   NaN
f  15.0  16.0  17.0  18.0
g   NaN   NaN   NaN   NaN

In [391]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [392]:
df.dropna(how='all', axis=0, inplace=False)

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN

In [393]:
df2 = df.copy()

In [394]:
df2.loc['g'].c1 = 0
df2.loc['g'].c3 = 0
df2

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   0.0   NaN   0.0   NaN NaN

In [395]:
df2.dropna(how='any', axis=1)

c1    c3
a   0.0   2.0
b   3.0   5.0
c   6.0   8.0
d   9.0  11.0
e  12.0  14.0
f  15.0  17.0
g   0.0   0.0

In [396]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [397]:
filled = df.fillna(0)
filled

c1    c2    c3    c4   c5
a   0.0   1.0   2.0  20.0  0.0
b   3.0   4.0   5.0   0.0  0.0
c   6.0   7.0   8.0   0.0  0.0
d   9.0  10.0  11.0   0.0  0.0
e  12.0  13.0  14.0   0.0  0.0
f  15.0  16.0  17.0  18.0  0.0
g   0.0   0.0   0.0   0.0  0.0

In [398]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [399]:
df.mean()

c1     7.5
c2     8.5
c3     9.5
c4    19.0
c5     NaN
dtype: float64

In [400]:
filled.mean()

c1    6.428571
c2    7.285714
c3    8.142857
c4    5.428571
c5    0.000000
dtype: float64

In [401]:
df.fillna(df.mean())

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0  19.0 NaN
c   6.0   7.0   8.0  19.0 NaN
d   9.0  10.0  11.0  19.0 NaN
e  12.0  13.0  14.0  19.0 NaN
f  15.0  16.0  17.0  18.0 NaN
g   7.5   8.5   9.5  19.0 NaN

In [402]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [403]:
df.c4.fillna(method="ffill")

<ipython-input-403-b726415f4972>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.c4.fillna(method="ffill")


a    20.0
b    20.0
c    20.0
d    20.0
e    20.0
f    18.0
g    18.0
Name: c4, dtype: float64

In [404]:
df

c1    c2    c3    c4  c5
a   0.0   1.0   2.0  20.0 NaN
b   3.0   4.0   5.0   NaN NaN
c   6.0   7.0   8.0   NaN NaN
d   9.0  10.0  11.0   NaN NaN
e  12.0  13.0  14.0   NaN NaN
f  15.0  16.0  17.0  18.0 NaN
g   NaN   NaN   NaN   NaN NaN

In [405]:
df.c4.fillna(method="bfill")

<ipython-input-405-69f7642b3e73>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.c4.fillna(method="bfill")


a    20.0
b    18.0
c    18.0
d    18.0
e    18.0
f    18.0
g     NaN
Name: c4, dtype: float64

# Pandas Gruplama

In [406]:
data = {
    'Kategori': ['Elektronik', 'Giyim', 'Giyim', 'Elektronik', 'Elektronik', 'Giyim'],
    'Marka': ['Samsung', 'Nike', 'Adidas', 'Apple', 'Sony', 'Levis'],
    'Fiyat': [2000, 300, 250, 5000, 1500, 150]
}

df = pd.DataFrame(data)
df

Kategori    Marka  Fiyat
0  Elektronik  Samsung   2000
1       Giyim     Nike    300
2       Giyim   Adidas    250
3  Elektronik    Apple   5000
4  Elektronik     Sony   1500
5       Giyim    Levis    150

In [407]:
grouped = df.groupby('Kategori').agg({'Fiyat': ['mean', 'min', 'max']})
print(grouped)

                  Fiyat            
                   mean   min   max
Kategori                           
Elektronik  2833.333333  1500  5000
Giyim        233.333333   150   300


In [408]:
grouped = df.groupby(['Kategori',"Marka"]).agg({'Fiyat': ['mean', 'min', 'max']})
print(grouped)

                     Fiyat            
                      mean   min   max
Kategori   Marka                      
Elektronik Apple    5000.0  5000  5000
           Samsung  2000.0  2000  2000
           Sony     1500.0  1500  1500
Giyim      Adidas    250.0   250   250
           Levis     150.0   150   150
           Nike      300.0   300   300


1. Bir listedeki isimlerin baş harflerini yazdıran uygulama

2. "Tamam" ifadesini görene kadar bir şeyler yazmanı isteyen uygulama (while)

3. Bir listedeki aynı isimleri teke indirecek bir uygulama

4. "Tamam" yazana kadar girdiğiniz kelimeleri, bir listeye ekleyen uygulama

5. Bir listedeki sadece stringleri döndüren bir döngü oluşturun

6. liste şeklindeki Celsius değerlerin fahrenayt a çevirecek uygulama

7. Tahmin oyunu  "from random import randint"  randint(0, 100)

8.  1 den 100 e kadar 3 er 3 er sayan uygulama

9. While döngüsü yine bir döngü  5 kere dönmesi gerekirken 3. hakkında yanan - döngüden çıkan ve while
döngüsünde de çıkan bir uygulama yazın

10.Girdiğiniz kelimedeki belirli harfleri yazdıran bir uygulama



In [2]:
isimler = ["Zafer", "Ege", "Ayşe", "Tamer", "Zafer"]

for isim in isimler:
      while isimler.count(isim) > 1:
                isimler.remove(isim)

print(isimler)

['Ege', 'Ayşe', 'Tamer', 'Zafer']


In [3]:
isimler = ["Zafer", "Ege", "Ayşe", "Tamer", "Zafer"]

set(isimler)

{'Ayşe', 'Ege', 'Tamer', 'Zafer'}

In [4]:
durum = False
kelimeler = []

while durum == False:
      cevap = input('Bir isim giriniz: ')

      if cevap.lower() == 'tamam':
            durum = True
      else:
            kelimeler.append(cevap)

Bir isim giriniz: zafer 
Bir isim giriniz: ege
Bir isim giriniz: ayşe
Bir isim giriniz: tamam


In [5]:
for kelime in kelimeler:
      print(kelime)

zafer 
ege
ayşe


In [6]:

kelimeler = []

while True:
  kelime = input("Bir seyler yaziniz: ")

  if kelime == "Tamam":
    print("Tamamlandi.")
    break # Burada 'Tamam' kelimesini eklememesi için döngüyü sonlandırdım.

  kelimeler.append(kelime)

print(kelimeler)

Bir seyler yaziniz: zafer
Bir seyler yaziniz: ege
Bir seyler yaziniz: tamam
Bir seyler yaziniz: Tamam
Tamamlandi.
['zafer', 'ege', 'tamam']


In [7]:
from random import randint

tahmin = False
sayi = randint(0, 100)
tahmin_sayisi = 0

while not tahmin:
      cevap = input('Tuttuğum sayıyı tahmin et ')
      tahmin_sayisi += 1

      if int(cevap) == sayi:
            print('Tebrikler  Bildin !!!')
            print(' {}. Tahminde buldun !'.format(tahmin_sayisi))
            break
      elif int(cevap) > sayi:
           print('Sayı {} daha küçük.'.format(cevap))
      elif int(cevap) < sayi:
           print('Sayı {} daha büyük.'.format(cevap))


Tuttuğum sayıyı tahmin et 50
Sayı 50 daha küçük.
Tuttuğum sayıyı tahmin et 25
Sayı 25 daha küçük.
Tuttuğum sayıyı tahmin et 37
Sayı 37 daha küçük.
Tuttuğum sayıyı tahmin et 43
Sayı 43 daha küçük.
Tuttuğum sayıyı tahmin et 46
Sayı 46 daha küçük.
Tuttuğum sayıyı tahmin et 44
Sayı 44 daha küçük.
Tuttuğum sayıyı tahmin et 45
Sayı 45 daha küçük.
Tuttuğum sayıyı tahmin et 10
Sayı 10 daha küçük.
Tuttuğum sayıyı tahmin et 8
Sayı 8 daha küçük.
Tuttuğum sayıyı tahmin et 4
Sayı 4 daha küçük.
Tuttuğum sayıyı tahmin et 2
Sayı 2 daha büyük.
Tuttuğum sayıyı tahmin et 3
Tebrikler  Bildin !!!
 12. Tahminde buldun !


Ödev

1- 3x2 lik 1 lerden oluşan bir matris oluşturun

2- 2x5 6'lardan oluşan bir matris oluşturun

3- 2-100 arası 2 şer atalayan bir array oluşturun

4- 3-10 arasında eşit dağılımlı 50 değer oluşturan bir array oluşturun


5- 10 boyutunda sıfırlardan oluşan bir vektör (array) oluşturun fakat 5. değeri 1 olsun

6- 0 dan 8 e kadar sıralı değerleri barındıran 3x3 lük bir matris oluşturun

7- Rasgele sayılardan oluşan 3x3x3 lük bir array oluşturun


8 - 10x10 rastgele bir array oluşturun. MAx ve min değerlerini bir değişkene atayın

9- Birlerden oluşan 5x3 matrisi birlerden oluşan 3x2 matrisle dot çarpın
