<a href="https://colab.research.google.com/github/merttguney/AI_106/blob/main/Gorev4_Mert_G%C3%BCney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1- 3x2 lik 1 lerden oluşan bir matris oluşturun**

In [1]:
import numpy as np # burada numpy kütüphanesini importladım

A = np.ones((3, 2), dtype = int) # tüm elemanları 1 olan, 3x2 boyutunda bir matris oluşturdum.
A

array([[1, 1],
       [1, 1],
       [1, 1]])

**2- 2x5 6'lardan oluşan bir matris oluşturun**

In [2]:
import numpy as np

A = np.ones((2, 5), dtype = int) * 6 # tüm elemanları 6 olan, 2x5 boyutunda bir matris oluşturdum.
A

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

**3- 2-100 arası 2 şer atlayan bir array oluşturun**

In [3]:
import numpy as np

A = np.arange(2, 101, 2) # 2 ile 100(dahil) arasındaki sayıları 2'şer atlayarak array oluşturdum
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**4- 3-10 arasında eşit dağılımlı 50 değer oluşturan bir array oluşturun**

In [17]:
import numpy as np

A = np.linspace(3, 10, 50) # 3 ile 10 arasında eşit dağılımlı 50 değer oluşturdum.
A

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

**5- 10 boyutunda sıfırlardan oluşan bir vektör (array) oluşturun fakat 5. değeri 1 olsun**

In [10]:
import numpy as np

A = np.zeros(10) # 10 boyutunda sıfırlardan oluşan bir vektör oluşturdum.
A[4] = 1 # 5.değeri(4.index) 1 yaptım.
A

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**6- 0 dan 8 e kadar sıralı değerler barındıran 3x3 lük bir matris oluşturun**

In [11]:
import numpy as np

A = np.arange(0, 9).reshape(3, 3) # 0 dan 8 e kadar sıralı değerler içeren 3x3 lük bir matris oluşturdum.
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**7- Rastgele sayılardan oluşan 3x3x3 lük bir array oluşturun**

In [12]:
import numpy as np

A = np.random.rand(3, 3, 3) # 0 ile 1 arasında rastgele sayılardan oluşan 3x3x3 lük bir array oluşturdum.
A

array([[[0.97344901, 0.08022396, 0.84602385],
        [0.99822245, 0.41536591, 0.77180828],
        [0.01921452, 0.11292912, 0.303245  ]],

       [[0.40867755, 0.99235159, 0.34605888],
        [0.35547662, 0.31099979, 0.86285006],
        [0.32937203, 0.20827585, 0.15296354]],

       [[0.97991058, 0.77257787, 0.89622615],
        [0.57636341, 0.62654006, 0.4484082 ],
        [0.94650241, 0.42219358, 0.66215287]]])

**8- 10x10 luk bir array oluşturun. Max ve min değerlerini bir değişkene atayın**

In [13]:
import numpy as np

A = np.random.randint(0, 100, size=(10, 10)) # 0 ile 100 arasında rastgele tam sayılardan oluşan 10x10'luk matris oluşturdum.

max_value = np.max(A)
min_value = np.min(A) # Maksimum ve minimum değerleri bir değişkene atama

print("Array:")
print(A)
print("\nMaximum Değer:", max_value)
print("Minimum Değer:", min_value)

Array:
[[13  6 43 30 46 19 20  6 46 46]
 [45 81 57 62 32 17 75 73 68 81]
 [45 18 22 31 59 81 21 45 42 72]
 [78 49 34 11 56 95 43 29 59 37]
 [31 37 71  6 73  6 36 16 54 42]
 [71 19 17 87 99 70 57 86 69 72]
 [62 84 97 37 70 92 48 73 75 72]
 [ 8 78 25 19 58 79 89 22  7  4]
 [14 75 37 95 38 56 80  1 31 14]
 [23  1 24 64 95 83 74  0 51 27]]

Maximum Değer: 99
Minimum Değer: 0


**9- Birlerden oluşan 5x3 matrisi birlerden oluşan 3x2 matrisle çarpın (dot)**

In [18]:
import numpy as np

A = np.ones((5, 3)) # 5x3 boyutunda birlerden oluşan matris.

B = np.ones((3, 2)) # 3x2 boyutunda birlerden oluşan matris.

result = np.dot(A, B) # Matrisler çarpıldo. (dot çarpım)

print("Sonuç Matrisi:")
print(result)

Sonuç Matrisi:
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
